title: IFBased
description:  bible stuff
remote_theme: tuur29/pages-themes-cayman
darkmode: true
color:
  header: "#000"
  gradient_left: "#ff2400"
  gradient_right: "#a020f0"
logo_url: 
gems:
- jekyll-seo-tag
