title: Based Bible Site
description:  Very based biblical Bible resources
remote_theme: tuur29/pages-themes-cayman
darkmode: true
color:
  header: "#000"
  gradient_left: "#fff666"
  gradient_right: "#fff666"
logo_url: 
gems:
- jekyll-seo-tag
theme: jekyll-theme-cayman-blog
